spring.application.name=Quantity-Measurement-App


spring.datasource.url=jdbc:mysql://localhost:3306/quantity_db
spring.datasource.username=root
spring.datasource.password=root@1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GOOGLE OAUTH
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

spring.security.oauth2.client.registration.google.scope=email,profile